// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://juqqfxnjhbkalxzjsxei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1cXFmeG5qaGJrYWx4empzeGVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDEyNTUsImV4cCI6MjA3MDU3NzI1NX0.9RK81iBByG-cdlUYq5B3jUgDHOgJyyGG-MR11WORU58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);